#!/usr/bin/env python3
"""Generate or check src/mods/mmx6_seamless_catalog.inc from an original disc.

The catalog holds metadata only: file extents, member descriptors, SHA-256 of
sector-padded member data, and the original loader-code guard. No game bytes.

Usage:
  py -3 tools/mmx6_seamless_catalog.py "Mega Man X6 (USA) (v1.1).bin" --check
  py -3 tools/mmx6_seamless_catalog.py "Mega Man X6 (USA) (v1.1).bin"   # rewrite
"""
import hashlib, os, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src', 'mods', 'mmx6_seamless_catalog.inc')
EXE_LBA_NAME = 'SLUS_013.95'
# Archive descriptor counts copied by the original initializers:
# 0x800147D0 copies 243 ROCK_X6.DAT descriptors, 0x80016780 copies 59 BIN ones.
ARCHIVES = (('ROCK_X6.DAT', 243), ('ROCK_X6.BIN', 59))
# Original code/data the synchronous adapter depends on. Live RAM must match
# these exact bytes before a load is served from resident data.
GUARDS = (
    (0x80010038, 0x80010068),  # sector-handler and handler-switch tables
    (0x80014D50, 0x80016704),  # sector reader, start/wait, callbacks, deferred queue
    (0x8006E348, 0x8006E354),  # deferred VRAM/SPU job table
    (0x80064894, 0x800648B4),  # CdReady wrapper
    (0x80064CB4, 0x80064CD4),  # CdGetSector wrapper
)


class Disc:
    def __init__(self, path):
        self.f = open(path, 'rb')

    def raw(self, lba):
        self.f.seek(lba * 2352)
        r = self.f.read(2352)
        if len(r) != 2352:
            raise SystemExit(f'short read at lba {lba}')
        return r

    def user(self, lba):
        r = self.raw(lba)
        return r[24:24 + 2048] if r[15] == 2 else r[16:16 + 2048]

    def files(self):
        pvd = self.user(16)
        if pvd[1:6] != b'CD001':
            raise SystemExit('not an ISO9660 image')
        root = pvd[156:156 + 34]
        lba, size = struct.unpack_from('<I', root, 2)[0], struct.unpack_from('<I', root, 10)[0]
        data = b''.join(self.user(lba + i) for i in range((size + 2047) // 2048))
        out, p = {}, 0
        while p < len(data):
            n = data[p]
            if not n:
                p = (p // 2048 + 1) * 2048
                continue
            rec = data[p:p + n]
            name = rec[33:33 + rec[32]].decode('ascii', 'replace').split(';')[0]
            out[name] = (struct.unpack_from('<I', rec, 2)[0], struct.unpack_from('<I', rec, 10)[0])
            p += n
        return out


def sha(b):
    return hashlib.sha256(b).hexdigest()


def generate(disc_path):
    disc = Disc(disc_path)
    files = disc.files()
    lines = ['// SLUS-01395 v1.1 original-disc metadata for Seamless Loading.',
             '// Generated by tools/mmx6_seamless_catalog.py. No copyrighted asset bytes.']
    exe_lba, exe_size = files[EXE_LBA_NAME]
    exe = b''.join(disc.user(exe_lba + i) for i in range((exe_size + 2047) // 2048))[:exe_size]
    text = exe[0x800:]
    guard = hashlib.sha256()
    for lo, hi in GUARDS:
        guard.update(text[lo - 0x80010000:hi - 0x80010000])
    lines.append('static const GuardRange guard_ranges[] = {')
    lines += [f'    {{0x{lo:08X}u, 0x{hi:08X}u}},' for lo, hi in GUARDS]
    lines.append('};')
    lines.append(f'static const char guard_sha256[] = "{guard.hexdigest()}";')
    lines.append('static const ArchiveFile archives[] = {')
    members = []
    for index, (name, count) in enumerate(ARCHIVES):
        lba, size = files[name]
        sectors = (size + 2047) // 2048
        body = b''.join(disc.user(lba + i) for i in range(sectors))
        tail = body[size:]
        if any(tail):
            raise SystemExit(f'{name}: nonzero padding after {size} bytes')
        header = body[:4096]
        end = 2
        for i in range(count):
            off, length = struct.unpack_from('<II', header, i * 8)
            if off != end or not length or off * 2048 + length > size:
                raise SystemExit(f'{name}[{i}]: unexpected descriptor {off},{length} (expected offset {end})')
            span = (length + 2047) // 2048
            members.append((index, i, off, length, sha(body[off * 2048:(off + span) * 2048])))
            end = off + span
        if end != sectors:
            raise SystemExit(f'{name}: descriptors cover {end} of {sectors} sectors')
        lines.append(f'    {{"{name}", {lba}u, {size}u, {count}u, "{sha(body)}"}},')
    lines.append('};')
    lines.append('static const ArchiveMember members[] = {')
    lines += [f'    {{{a}u, {i}u, {o}u, {n}u, "{h}"}},' for a, i, o, n, h in members]
    lines.append('};')
    return '\n'.join(lines) + '\n'


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    text = generate(sys.argv[1])
    if '--check' in sys.argv[2:]:
        current = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if current != text:
            raise SystemExit(f'{OUT} does not match the supplied disc')
        print('catalog matches disc')
        return
    open(OUT, 'w', encoding='utf-8', newline='\n').write(text)
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
